### ISSUE TITLE
The AFL fuzzing states doesn;t show

### ISSUE THREAD

**Issue by dgh05t** [HexHive/USBFuzz#2]
Hi
When I run USBFuzz , It runs over the seeds , and hangs at "Fuzzing test case #0 (30 total, 0 uniq crashes found)...", doesn't show the fuzzing stats as usual( but  the qemu seems in a fuzzing loop), is this normal?

**Comment by wenwenyuyu12138** [comment]
Hi, how do you run the USBFuzz. I meet the ' Fork Server handshake Failed ' problem.
